server:
  port: 9800
  tomcat:
    threads:
      min-spare: 20
      max: 200
    # 하나의 Tomcat 인스턴스가 유지할 수 있는 Connection의 수
    # 현재 연결되어 있는 실제 Connection의 수가 아니고, 현재 사용중인 Socket FD(File Descriptor)의 수를 의미한다.
    max-connections: 8192

spring:
  profiles:
    active: dev

  data:
    # Application이 종료 되어이야 MongoDB Connection이 끊기는 부분을 확인했음.
    # db.serverStatus().connections 쿼리를 통해 Connection 상태를 확인할 수 있음
    # current : 현재 연결중인 Connection 수
    # available : 사용 가능한 Connection 수
    # totalCreated : 현재까지 연결된 모든 Connection 수 (닫은 연결도 포함됨.)
    mongodb:
#      uri: mongodb://product:1234@localhost:27017/product_db?maxPoolSize=100&waitQueueTimeoutMS=3000&maxIdleTimeMS=1800000&maxLifeTimeMS=1800000
      uri: mongodb://localhost:27017/product_db?maxPoolSize=100&waitQueueTimeoutMS=3000&maxIdleTimeMS=1800000&maxLifeTimeMS=1800000

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: changeme
    ssl:
      enabled: false
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
        acknowledge-mode: manual

logging:
  level:
    com.rabbitmq.client: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
