server:
  port: 9800
  tomcat:
    threads:
      min-spare: 20
      max: 200
    # Request Queue의 길이
    accept-count: 10
    # 하나의 Tomcat 인스턴스가 유지할 수 있는 Connection의 수
    # 현재 연결되어 있는 실제 Connection의 수가 아니고, 현재 사용중인 Socket FD(File Descriptor)의 수를 의미한다.
    max-connections: 8192

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: changeme
    ssl:
      enabled: false
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
        acknowledge-mode: manual

logging:
  level:
    com:
      rabbitmq:
        client: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
