server:
  port: 9800

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: changeme
    ssl:
      enabled: false
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
        acknowledge-mode: manual

logging:
  level:
    com:
      rabbitmq:
        client: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
