version: '3.3'

services:
  product-write-mysql:
    image: product-write-mysql
    volumes:
      - ./write/mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./write/mysql-config-files/:/etc/mysql/conf.d
    restart: always
    container_name: product-write-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    ports:
      - '9030:3306'
    networks:
      product_mysql_net:
        ipv4_address: 172.16.0.10

  product-read-mysql:
    image: product-read-mysql
    volumes:
      - ./read/mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./read/mysql-config-files/:/etc/mysql/conf.d
    restart: always
    container_name: product-read-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    ports:
      - '9031:3306'
    networks:
      product_mysql_net:
        ipv4_address: 172.16.0.11
    depends_on:
      - 'product-write-mysql'

networks:
  product_mysql_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
